### ISSUE TITLE
How to apply MaterialColorUtilities only on Android?

### ISSUE THREAD

**Issue by veikkoeeva** [albi005/MaterialColorUtilities#21]
This is a Maui-n00b question, but maybe possible to ask here. Maybe this would be useful for others too.

In the instructions you show a helpful way on how to define the colors as in
```diff
<?xml version = "1.0" encoding = "UTF-8" ?>
<Application xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:YourBeautifulApp"
             x:Class="YourBeautifulApp.App">
    <Application.Resources>
+       <Color x:Key="Primary" />
+       <Color x:Key="PrimaryContainer" />
```

Let's assume one would apply this in Android application, but then do Fluent Design on Windows application. What would be the proper way to add this in Maui application in that case?

When using the Maui Single project way, I think the way is to add the colors to `Platforms -> Android -> Resources -> values -> colors.xml`. Then either `#if-#def` in the main `MauiProgram.cs` this library or in `Platforms -> Android -> MainApplication.cs` include it. Would this be correct?

Very nice effort!

**Comment by albi005** [comment]
If I understand correctly, you want dynamic colors only on Android. If so, you can just do
```csharp
        MauiAppBuilder builder = MauiApp
            .CreateBuilder()
#if ANDROID
            .UseMaterialDynamicColors()
#endif
            .UseMauiApp<App>();
```
in `MauiProgram.cs`. 

The color definitions in `App.xaml` are only needed so Visual Studio knows that those colors are available as resources and it will suggest them when writing XAML:
![image](https://user-images.githubusercontent.com/22728934/183057830-b621a17d-8673-48dd-9a53-032bda627dbf.png)
You can just leave them there, they shouldn't interfere with anything.
