### ISSUE TITLE
How can you use it with mdc-maui?

### ISSUE THREAD

**Issue by Gami13** [albi005/MaterialColorUtilities#35]
The author described it in https://github.com/mdc-maui/mdc-maui/issues/36#issuecomment-1811473881 but never said what `_appResources` is, does't seem to work when initializing it to `Application.Current.Resources`

**Comment by albi005** [comment]
The base `MaterialColorService` has an `_appResources` field. Override the `Initialize` method to get it (or `Application.Current.Resources` should also work):

```csharp
public class CustomMaterialColorService : MaterialColorService<CorePalette, Scheme<uint>, Scheme<Color>, LightSchemeMapper, DarkSchemeMapper>
{
  private ResourceDictionary _appResources = null!;
  // ...
  public override void Initialize(ResourceDictionary resourceDictionary)
  {
      _appResources = resourceDictionary;
      base.Initialize(resourceDictionary);
  }
}
```

I also forgot to add that you [have to call](https://github.com/albi005/MaterialColorUtilities/blob/main/MaterialColorUtilities.Maui/README.md#getting-started) `Initialize` in `App.xaml.cs` before creating any pages:

```diff
+using MaterialColorUtilities.Maui;

public class App : Application
{
    public App(CustomMaterialColorService colorService)
    {
+       colorService.Initialize(this.Resources);
        
        MainPage = // ...
    }
}
```

**Comment by Gami13** [comment]
This worked! Thank you so much for your help!

**Comment by Gami13** [comment]
In fact it worked so well that it fixed mdc-maui's bug with cards always using light mode, amazing
